# Import

In [1]:
# importing numpy to document
import numpy as np

# Check Version

In [2]:
# checking numpy version
print(np.__version__)

1.24.3


# Creating NumPy

In [3]:
# creating a numpy array from list
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
# use a tuple to create a numpy array
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


# Check Data Types

In [5]:
# checking data types of numpy array
print(type(arr))

<class 'numpy.ndarray'>


# Dimension on Numpy Array

A dimension in arrays is one level of array depth (nested array)

In [6]:
# 0-D Arrays
arr_0 = np.array(42)
print(arr_0)

42


In [7]:
# Creating 1-D Arrays
arr_1 = np.array([1,2,3,4,5])
print(arr_1)

[1 2 3 4 5]


In [11]:
# Creating 2-D Arrays
arr_2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
# Creating 3-D Arrays
arr_3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
print(arr_3)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


# Check how many dimension on NumPy Array

In [14]:
# Check how many dimensions the array
print(arr_2.ndim)

2


In [15]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
# Create an arrays with 5 dimensions and verify that it has 5 dimension
arr5 = np.array([1,2,3,4], ndmin=5)
print(arr5)

[[[[[1 2 3 4]]]]]


In [17]:
arr5 = np.array([1,2,3,4], ndmin=5)
print(arr5)
print('number of dimensions :', arr5.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [18]:
# get the first element from the following array
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [19]:
# get the third and fourth element from the following array
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [20]:
# Access the element on the first row, second column
arr = np.array([[1, 2, 3, 4] , [5, 6, 7, 8]])
print('2nd element on 1st row :', arr[0, 1])

2nd element on 1st row : 2


In [21]:
# Access the element on the 2nd row, 5th column
arr = np.array([[1, 2, 3, 4, 5] , [6, 7, 8, 9, 10]])
print('5th element on 2nd row :', arr[1, 4])

5th element on 2nd row : 10


# Task 1

In [22]:
# import
import numpy as np

# cek version
print(np.__version__)

# contoh numpy 2D array
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr1)

# type data
print(type(arr1))

1.24.3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


# Task 2

In [23]:
# 0-D array
arr0 = np.array(10)
print(arr0)

10


In [24]:
# 1-D array
arr1 = np.array(['ninys', 'elsha', 'cristin', 'tria'])
print(arr1)

['ninys' 'elsha' 'cristin' 'tria']


In [25]:
# 2-D array
arr2 = np.array([[2, 2.5, 3], [4, 6, 8], ['ninys','elsha','cristin']])
print(arr2)

[['2' '2.5' '3']
 ['4' '6' '8']
 ['ninys' 'elsha' 'cristin']]


# Task 3

In [26]:
# create array
x = np.array(10)
y = np.array([20, 21, 22])
z = np.array([[10, 20],['ninys', 'data']])

print(x.ndim)
print(y.ndim)
print(z.ndim)

0
1
2


In [28]:
arr10 = np.array([2, 4, 6], ndmin = 3)
print(arr10)
print ('number of dimensions :', arr10.ndim)

[[[2 4 6]]]
number of dimensions : 3


# Task 4

In [29]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

first_row = arr2[0, :]
print('Slicing baris pertama :', first_row)

Slicing baris pertama : [1 2 3]
